stages:
  download:
    cmd: python scripts/download_cifake.py
    deps:
      - scripts/download_cifake.py
    outs:
      - data/processed:
          persist: true

  validate:
    cmd: python -m src.data.validate --data-dir data/processed --output reports/data_validation.json
    deps:
      - src/data/validate.py
      - data/processed
    outs:
      - reports/data_validation.json:
          cache: false

  train:
    cmd: python -m src.training.train --config configs/train_config.yaml
    deps:
      - src/training/train.py
      - src/training/model.py
      - src/training/dataset.py
      - src/training/augmentation.py
      - configs/train_config.yaml
      - data/processed
    outs:
      - models/checkpoints/best_model.pt:
          persist: true
